URL_SERVICE = "https://cnt-aa59c15f-d75c-4982-a81f-4d6573dd66eb.containerhub.tripleten-services.com"
#DOC_PATH = "/docs/"
#LOG_MAIN_PATH = "/api/logs/main/"
#USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
#PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
KITS_PATH = "/api/v1/kits"
KITS_SAVE_PATH = "/api/v1/kits/search?name=Mi%20Conjunto"