URL_SERVICE = "https://cnt-a85485b0-70a1-409f-b9eb-7809b8ae20de.containerhub.tripleten-services.com"
#DOC_PATH = "/docs/"
#LOG_MAIN_PATH = "/api/logs/main/"
#USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
#PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
KITS_PATH = "/api/v1/kits"
KITS_SAVE_PATH = "/api/v1/kits/search?name=Mi%20Conjunto"